### ISSUE TITLE
Move inputs of expanded node to the distance same as for compact node

### ISSUE THREAD

**Issue by pmlodawski** [luna/basegl-ui#58]

**Comment by piotrMocz** [comment]
The distance is the same but the ports are not aligned with the sliders, which doesn't look so good -- see the picture.

<img width="266" alt="screen shot 2018-10-18 at 10 31 49" src="https://user-images.githubusercontent.com/3109645/47141565-456b9680-d2c1-11e8-9537-bffc7428aaf6.png">

**Comment by sylwiabr** [comment]
something is not working properly:
![zrzut ekranu z 2018-10-30 18-23-15](https://user-images.githubusercontent.com/12892578/47737658-b0c64880-dc71-11e8-9c76-322d1a218c16.png)
the used code is from Dataframes repository commit f457a6cac4536080a5033e0df3121c322625088a function timeseries

**Comment by pmlodawski** [comment]
I added separate issues for that: https://github.com/luna/basegl-ui/issues/107 https://github.com/luna/basegl-ui/issues/108
